### PR TITLE
Added fields to sites and plots

### PR DESCRIPTION
**Pull request by jwest60**
#57 

- added species and shrubs field to site form
- added recorders field to plot form
- added recorders information to the plot page (Plants.vue)

### CODE REVIEW

**Comment by jwest60** [comment]
The species / shrubs fields now use [Select2](https://www.npmjs.com/package/v-select2-component) multiselect

**Comment by almasaeed2010** [comment]
Works as expected 👍 

- [ ] We need to display the list of trees on the site page under Site Information on the right column.

**Comment by almasaeed2010** [comment]
the google chrome console shows an error saying that the id prop for the tokens field is not unique. We need to allow the component to have an id prop

**Comment by jwest60** [comment]
Added overstory species and shrub species fields to site info

image

Also set unique ids for the Select2 components

**Pull request merged**
